module.exports = {
  I2C_ADDRESS: 0x24 >> 1,
  // Section 7 - Commands supported (page 65)
  // Miscellaneous
  COMMAND_DIAGNOSE: 0x00,
  COMMAND_GET_FIRMWARE_VERSION: 0x02,
  COMMAND_GET_GENERAL_STATUS: 0x04,
  COMMAND_READ_REGISTER: 0x06,
  COMMAND_WRITE_REGISTER: 0x08,
  COMMAND_READ_GPIO: 0x0C,
  COMMAND_WRITE_GPIO: 0x0E,
  COMMAND_SET_SERIAL_BAUD_RATE: 0x10,
  COMMAND_SET_PARAMETERS: 0x12,
  COMMAND_SAMCONFIGURATION: 0x14,
  COMMAND_POWER_DOWN: 0x16
};
